# Generated by Django 2.2.4 on 2020-04-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='civil_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='NA', max_length=500)),
                ('answer_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('appeal_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('appealed_by', models.CharField(blank=True, default='NA', max_length=500)),
                ('attorney_fees', models.CharField(blank=True, default='NA', max_length=500)),
                ('case_number', models.CharField(blank=True, default='NA', max_length=500)),
                ('case_type', models.CharField(blank=True, default='NA', max_length=500)),
                ('costs', models.CharField(blank=True, default='NA', max_length=500)),
                ('court', models.CharField(blank=True, default='NA', max_length=500)),
                ('date_satisfaction_filed', models.CharField(blank=True, default='NA', max_length=500)),
                ('debt_type', models.CharField(blank=True, default='NA', max_length=500)),
                ('defendant_info', models.CharField(blank=True, default='NA', max_length=500)),
                ('filed_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('further_case_info', models.CharField(blank=True, default='NA', max_length=500)),
                ('garnishee', models.CharField(blank=True, default='NA', max_length=500)),
                ('garnishee_answer', models.CharField(blank=True, default='NA', max_length=500)),
                ('hearing_info', models.CharField(blank=True, default='NA', max_length=500)),
                ('homestead_exemption_waived', models.CharField(blank=True, default='NA', max_length=500)),
                ('interest_award', models.CharField(blank=True, default='NA', max_length=500)),
                ('is_judgement_satisifed', models.CharField(blank=True, default='NA', max_length=500)),
                ('judgment', models.CharField(blank=True, default='NA', max_length=500)),
                ('number_of_checks_received', models.CharField(blank=True, default='NA', max_length=500)),
                ('other_amount', models.CharField(blank=True, default='NA', max_length=500)),
                ('other_awarded', models.CharField(blank=True, default='NA', max_length=500)),
                ('plaintiff_info', models.CharField(blank=True, default='NA', max_length=500)),
                ('possession', models.CharField(blank=True, default='NA', max_length=500)),
                ('principal_amount', models.CharField(blank=True, default='NA', max_length=500)),
                ('writ_issue_date', models.CharField(blank=True, default='NA', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='crim_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='NA', max_length=500)),
                ('aka1', models.CharField(blank=True, default='NA', max_length=500)),
                ('aka2', models.CharField(blank=True, default='NA', max_length=500)),
                ('amended_case_type', models.CharField(blank=True, default='NA', max_length=500)),
                ('amended_charge', models.CharField(blank=True, default='NA', max_length=500)),
                ('amended_code', models.CharField(blank=True, default='NA', max_length=500)),
                ('arrest_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('case_number', models.CharField(blank=True, default='NA', max_length=500)),
                ('case_type', models.CharField(blank=True, default='NA', max_length=500)),
                ('charge', models.CharField(blank=True, default='NA', max_length=500)),
                ('code_section', models.CharField(blank=True, default='NA', max_length=500)),
                ('complainant', models.CharField(blank=True, default='NA', max_length=500)),
                ('costs', models.CharField(blank=True, default='NA', max_length=500)),
                ('court', models.CharField(blank=True, default='NA', max_length=500)),
                ('crim_class', models.CharField(blank=True, default='NA', max_length=500)),
                ('date_of_birth', models.CharField(blank=True, default='NA', max_length=500)),
                ('defense_attorney', models.CharField(blank=True, default='NA', max_length=500)),
                ('filed_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('final_disposition', models.CharField(blank=True, default='NA', max_length=500)),
                ('fine', models.CharField(blank=True, default='NA', max_length=500)),
                ('fine_costs_due', models.CharField(blank=True, default='NA', max_length=500)),
                ('fine_costs_paid', models.CharField(blank=True, default='NA', max_length=500)),
                ('fine_costs_paid_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('gender', models.CharField(blank=True, default='NA', max_length=500)),
                ('hearing_info', models.CharField(blank=True, default='NA', max_length=500)),
                ('locality', models.CharField(blank=True, default='NA', max_length=500)),
                ('name', models.CharField(blank=True, default='NA', max_length=500)),
                ('offense_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('operator_license_restriction_codes', models.CharField(blank=True, default='NA', max_length=500)),
                ('operator_license_suspension_effective_date', models.CharField(blank=True, default='NA', max_length=500)),
                ('operator_license_suspension_time', models.CharField(blank=True, default='NA', max_length=500)),
                ('probation_starts', models.CharField(blank=True, default='NA', max_length=500)),
                ('probation_time', models.CharField(blank=True, default='NA', max_length=500)),
                ('probation_type', models.CharField(blank=True, default='NA', max_length=500)),
                ('race', models.CharField(blank=True, default='NA', max_length=500)),
                ('sentence_suspended_time', models.CharField(blank=True, default='NA', max_length=500)),
                ('sentence_time', models.CharField(blank=True, default='NA', max_length=500)),
                ('status', models.CharField(blank=True, default='NA', max_length=500)),
                ('vasap', models.CharField(blank=True, default='NA', max_length=500)),
            ],
        ),
    ]
