# Generated by Django 3.2.5 on 2022-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, max_length=3, null=True)),
                ('filed_date', models.CharField(blank=True, max_length=10, null=True)),
                ('filing_type', models.CharField(blank=True, max_length=100, null=True)),
                ('filing_fee_paid', models.CharField(blank=True, max_length=3, null=True)),
                ('number_of_plaintiffs', models.CharField(blank=True, max_length=5, null=True)),
                ('number_of_defendants', models.CharField(blank=True, max_length=6, null=True)),
                ('commenced_by', models.CharField(blank=True, max_length=30, null=True)),
                ('bond', models.CharField(blank=True, max_length=15, null=True)),
                ('complex_case', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ordered_to_mediation', models.CharField(blank=True, max_length=3, null=True)),
                ('judgment', models.CharField(blank=True, max_length=10, null=True)),
                ('final_order_date', models.CharField(blank=True, max_length=10, null=True)),
                ('appealed_date', models.CharField(blank=True, max_length=10, null=True)),
                ('concluded_by', models.CharField(blank=True, max_length=35, null=True)),
                ('plaintiff_1_trading_as', models.CharField(blank=True, max_length=30, null=True)),
                ('plaintiff_2_trading_as', models.CharField(blank=True, max_length=30, null=True)),
                ('plaintiff_3_trading_as', models.CharField(blank=True, max_length=30, null=True)),
                ('plaintiff_1_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('plaintiff_2_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('plaintiff_3_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('defendant_1_trading_as', models.CharField(blank=True, max_length=30, null=True)),
                ('defendant_2_trading_as', models.CharField(blank=True, max_length=30, null=True)),
                ('defendant_3_trading_as', models.CharField(blank=True, max_length=30, null=True)),
                ('defendant_1_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('defendant_2_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('defendant_3_attorney', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
