from django.db import models


class CircuitCriminal(models.Model):

    hearing_date = models.CharField(max_length=10, blank=True, null=True)
    hearing_result = models.CharField(max_length=108, blank=True, null=True)
    hearing_jury = models.CharField(max_length=3, blank=True, null=True)
    hearing_plea = models.CharField(max_length=17, blank=True, null=True)
    hearing_type = models.CharField(max_length=41, blank=True, null=True)
    hearing_room = models.CharField(max_length=4, blank=True, null=True)
    fips = models.CharField(max_length=3, blank=True, null=True)
    filed = models.CharField(max_length=10, blank=True, null=True)
    commenced_by = models.CharField(max_length=46, blank=True, null=True)
    locality = models.CharField(max_length=20, blank=True, null=True)
    sex = models.CharField(max_length=6, blank=True, null=True)
    race = models.CharField(max_length=40, blank=True, null=True)
    address = models.CharField(max_length=40, blank=True, null=True)
    charge = models.CharField(max_length=48, blank=True, null=True)
    code_section = models.CharField(max_length=20, blank=True, null=True)
    charge_type = models.CharField(max_length=39, blank=True, null=True)
    offense_class = models.CharField(max_length=3, blank=True, null=True)
    offense_date = models.CharField(max_length=10, blank=True, null=True)
    arrest_date = models.CharField(max_length=10, blank=True, null=True)
    disposition_code = models.CharField(max_length=32, blank=True, null=True)
    disposition_date = models.CharField(max_length=10, blank=True, null=True)
    concluded_by = models.CharField(max_length=26, blank=True, null=True)
    amended_charge = models.CharField(max_length=48, blank=True, null=True)
    amended_code_section = models.CharField(max_length=19, blank=True, null=True)
    amended_charge_type = models.CharField(max_length=39, blank=True, null=True)
    jail_penitentiary = models.CharField(max_length=12, blank=True, null=True)
    concurrent_consecutive = models.CharField(max_length=11, blank=True, null=True)
    life_death = models.CharField(max_length=13, blank=True, null=True)
    sentence_time = models.CharField(max_length=7, blank=True, null=True)
    sentence_suspended = models.CharField(max_length=7, blank=True, null=True)
    operator_license_suspension_time = models.CharField(max_length=7, blank=True, null=True)
    fine_amount = models.CharField(max_length=9, blank=True, null=True)
    costs = models.CharField(max_length=10, blank=True, null=True)
    fines_cost_paid = models.CharField(max_length=3, blank=True, null=True)
    program_type = models.CharField(max_length=41, blank=True, null=True)
    probation_type = models.CharField(max_length=22, blank=True, null=True)
    probation_time = models.CharField(max_length=7, blank=True, null=True)
    probation_starts = models.CharField(max_length=10, blank=True, null=True)
    court_dmv_surrender = models.CharField(max_length=65, blank=True, null=True)
    driver_improvement_clinic = models.CharField(max_length=3, blank=True, null=True)
    driving_restrictions = models.CharField(max_length=3, blank=True, null=True)
    restriction_effective_date = models.CharField(max_length=10, blank=True, null=True)
    restriction_end_date = models.CharField(max_length=10, blank=True, null=True)
    va_alcohol_safety_action = models.CharField(max_length=3, blank=True, null=True)
    restitution_paid = models.CharField(max_length=3, blank=True, null=True)
    restitution_amount = models.CharField(max_length=10, blank=True, null=True)
    military = models.CharField(max_length=14, blank=True, null=True)
    traffic_fatality = models.CharField(max_length=3, blank=True, null=True)
    appealed_date = models.CharField(max_length=10, blank=True, null=True)
    person_id = models.CharField(max_length=15, blank=True, null=True)