# Generated by Django 3.2.5 on 2022-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(blank=True, max_length=3, null=True)),
                ('filed_date', models.CharField(blank=True, max_length=10, null=True)),
                ('case_type', models.CharField(blank=True, max_length=35, null=True)),
                ('debt_type', models.CharField(blank=True, max_length=40, null=True)),
                ('judgment', models.CharField(blank=True, max_length=25, null=True)),
                ('costs', models.CharField(blank=True, max_length=10, null=True)),
                ('attorney_fees', models.CharField(blank=True, max_length=10, null=True)),
                ('principal_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('other_amount', models.CharField(blank=True, max_length=10, null=True)),
                ('interest_award', models.CharField(blank=True, max_length=70, null=True)),
                ('possession', models.CharField(blank=True, max_length=10, null=True)),
                ('writ_issued_date', models.CharField(blank=True, max_length=10, null=True)),
                ('homestead_exemption_waived', models.CharField(blank=True, max_length=3, null=True)),
                ('is_judgment_satisfied', models.CharField(blank=True, max_length=5, null=True)),
                ('date_satisfaction_filed', models.CharField(blank=True, max_length=10, null=True)),
                ('other_awarded', models.CharField(blank=True, max_length=70, null=True)),
                ('further_case_information', models.CharField(blank=True, max_length=65, null=True)),
                ('garnishee', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('garnishee_answer', models.CharField(blank=True, max_length=15, null=True)),
                ('answer_date', models.CharField(blank=True, max_length=10, null=True)),
                ('number_of_checks_received', models.CharField(blank=True, max_length=5, null=True)),
                ('appeal_date', models.CharField(blank=True, max_length=10, null=True)),
                ('appealed_by', models.CharField(blank=True, max_length=15, null=True)),
                ('writ_of_eviction_issued_date', models.CharField(blank=True, max_length=10, null=True)),
                ('writ_of_fieri_facias_issued_date', models.CharField(blank=True, max_length=3, null=True)),
                ('plaintiff_1_DBATA', models.CharField(blank=True, max_length=50, null=True)),
                ('plaintiff_1_address', models.CharField(blank=True, max_length=40, null=True)),
                ('plaintiff_1_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('plaintiff_2_DBATA', models.CharField(blank=True, max_length=50, null=True)),
                ('plaintiff_2_address', models.CharField(blank=True, max_length=40, null=True)),
                ('plaintiff_2_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('plaintiff_3_DBATA', models.CharField(blank=True, max_length=50, null=True)),
                ('plaintiff_3_address', models.CharField(blank=True, max_length=40, null=True)),
                ('plaintiff_3_attorney', models.CharField(blank=True, max_length=35, null=True)),
                ('defendant_1_DBATA', models.CharField(blank=True, max_length=50, null=True)),
                ('defendant_1_address', models.CharField(blank=True, max_length=50, null=True)),
                ('defendant_1_attorney', models.CharField(blank=True, max_length=30, null=True)),
                ('defendant_2_DBATA', models.CharField(blank=True, max_length=50, null=True)),
                ('defendant_2_address', models.CharField(blank=True, max_length=50, null=True)),
                ('defendant_2_attorney', models.CharField(blank=True, max_length=30, null=True)),
                ('defendant_3_DBATA', models.CharField(blank=True, max_length=50, null=True)),
                ('defendant_3_address', models.CharField(blank=True, max_length=50, null=True)),
                ('defendant_3_attorney', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
