from django.db import models


class DistrictCriminal(models.Model):

    hearing_date = models.CharField(max_length=10, blank=True, null=True)
    hearing_result = models.CharField(max_length=9, blank=True, null=True)
    hearing_plea = models.CharField(max_length=17, blank=True, null=True)
    hearing_continuance_code = models.CharField(max_length=22, blank=True, null=True)
    hearing_type = models.CharField(max_length=54, blank=True, null=True)
    hearing_courtroom = models.CharField(max_length=4, blank=True, null=True)
    fips = models.CharField(max_length=3, blank=True, null=True)
    filed_date = models.CharField(max_length=10, blank=True, null=True)
    locality = models.CharField(max_length=20, blank=True, null=True)
    status = models.CharField(max_length=24, blank=True, null=True)
    defense_attorney = models.CharField(max_length=30, blank=True, null=True)
    address = models.CharField(max_length=40, blank=True, null=True)
    gender = models.CharField(max_length=6, blank=True, null=True)
    race = models.CharField(max_length=42, blank=True, null=True)
    charge = models.CharField(max_length=57, blank=True, null=True)
    code_section = models.CharField(max_length=15, blank=True, null=True)
    case_type = models.CharField(max_length=53, blank=True, null=True)
    offense_class = models.CharField(max_length=3, blank=True, null=True)
    offense_date = models.CharField(max_length=10, blank=True, null=True)
    arrest_date = models.CharField(max_length=10, blank=True, null=True)
    complainant = models.CharField(max_length=30, blank=True, null=True)
    amended_charge = models.CharField(max_length=55, blank=True, null=True)
    amended_code = models.CharField(max_length=15, blank=True, null=True)
    amended_case_type = models.CharField(max_length=53, blank=True, null=True)
    final_disposition = models.CharField(max_length=41, blank=True, null=True)
    sentence_time = models.CharField(max_length=5, blank=True, null=True)
    sentence_suspended_time = models.CharField(max_length=5, blank=True, null=True)
    probation_type = models.CharField(max_length=22, blank=True, null=True)
    probation_time = models.CharField(max_length=7, blank=True, null=True)
    probation_starts = models.CharField(max_length=48, blank=True, null=True)
    operator_license_suspension_time = models.CharField(max_length=7, blank=True, null=True)
    restriction_effective_date = models.CharField(max_length=10, blank=True, null=True)
    restriction_end_date = models.CharField(max_length=10, blank=True, null=True)
    operator_license_restriction_codes = models.CharField(max_length=767, blank=True, null=True)
    fine = models.CharField(max_length=7, blank=True, null=True)
    costs = models.CharField(max_length=8, blank=True, null=True)
    fine_costs_due = models.CharField(max_length=10, blank=True, null=True)
    fine_costs_paid = models.CharField(max_length=3, blank=True, null=True)
    fine_costs_paid_date = models.CharField(max_length=10, blank=True, null=True)
    vasap = models.CharField(max_length=3, blank=True, null=True)
    fine_costs_past_due = models.CharField(max_length=3, blank=True, null=True)
    person_id = models.CharField(max_length=15, blank=True, null=True)