# Generated by Django 3.2.5 on 2022-01-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit_criminal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circuitcriminal',
            old_name='commencedby',
            new_name='commenced_by',
        ),
    ]
