from django.db import models

"""
TODO: 
- convert date fields to date types, and number fields to number types
"""

class civil_case(models.Model):
    address = models.CharField(default='NA', max_length=500,blank=True)
    answer_date = models.CharField(default='NA', max_length=500,blank=True)
    appeal_date = models.CharField(default='NA', max_length=500,blank=True)
    appealed_by = models.CharField(default='NA', max_length=500,blank=True)
    attorney_fees = models.CharField(default='NA', max_length=500,blank=True)
    case_number = models.CharField(default='NA', max_length=500,blank=True)
    case_type = models.CharField(default='NA', max_length=500,blank=True) 
    costs = models.CharField(default='NA', max_length=500,blank=True)
    court = models.CharField(default='NA', max_length=500,blank=True) 
    date_satisfaction_filed = models.CharField(default='NA', max_length=500,blank=True)
    debt_type = models.CharField(default='NA', max_length=500,blank=True)
    defendant_info = models.CharField(default='NA', max_length=500,blank=True)
    filed_date = models.CharField(default='NA', max_length=500,blank=True)
    further_case_info = models.CharField(default='NA', max_length=500,blank=True)
    garnishee = models.CharField(default='NA', max_length=500,blank=True)
    garnishee_answer = models.CharField(default='NA', max_length=500,blank=True)
    hearing_info = models.CharField(default='NA', max_length=500,blank=True)
    homestead_exemption_waived = models.CharField(default='NA', max_length=500,blank=True)
    interest_award = models.CharField(default='NA', max_length=500,blank=True)
    is_judgement_satisifed = models.CharField(default='NA', max_length=500,blank=True)
    judgment = models.CharField(default='NA', max_length=500,blank=True)
    number_of_checks_received = models.CharField(default='NA', max_length=500,blank=True)
    other_amount = models.CharField(default='NA', max_length=500,blank=True)
    other_awarded = models.CharField(default='NA', max_length=500,blank=True)
    plaintiff_info = models.CharField(default='NA', max_length=500,blank=True)
    possession = models.CharField(default='NA', max_length=500,blank=True)
    principal_amount = models.CharField(default='NA', max_length=500,blank=True)
    writ_issue_date = models.CharField(default='NA', max_length=500,blank=True)

    def __str__(self):
        """Return a human readable representation of the model instance."""
        # return f"this is a {self.case_type} case adjudicated in {self.court} and filed on {self.filed_date}"
        return "this is a civil case filed on " + str(self.filed_date) + " identified by case number " + str(self.case_number)

class crim_case(models.Model):
    address = models.CharField(default='NA', max_length=500,blank=True)
    aka1 = models.CharField(default='NA', max_length=500,blank=True)
    aka2 = models.CharField(default='NA', max_length=500,blank=True)
    amended_case_type  = models.CharField(default='NA', max_length=500,blank=True)
    amended_charge = models.CharField(default='NA', max_length=500,blank=True)
    amended_code = models.CharField(default='NA', max_length=500,blank=True)
    arrest_date = models.CharField(default='NA', max_length=500,blank=True)
    case_number = models.CharField(default='NA', max_length=500,blank=True)
    case_type = models.CharField(default='NA', max_length=500,blank=True)
    charge = models.CharField(default='NA', max_length=500,blank=True)
    code_section = models.CharField(default='NA', max_length=500,blank=True)
    complainant = models.CharField(default='NA', max_length=500,blank=True)
    costs = models.CharField(default='NA', max_length=500,blank=True)
    court = models.CharField(default='NA', max_length=500,blank=True)
    crim_class = models.CharField(default='NA', max_length=500,blank=True)
    date_of_birth = models.CharField(default='NA', max_length=500,blank=True)
    defense_attorney = models.CharField(default='NA', max_length=500,blank=True)
    filed_date = models.CharField(default='NA', max_length=500,blank=True)
    final_disposition = models.CharField(default='NA', max_length=500,blank=True)
    fine = models.CharField(default='NA', max_length=500,blank=True)
    fine_costs_due = models.CharField(default='NA', max_length=500,blank=True)
    fine_costs_paid = models.CharField(default='NA', max_length=500,blank=True)
    fine_costs_paid_date = models.CharField(default='NA', max_length=500,blank=True)
    gender = models.CharField(default='NA', max_length=500,blank=True)
    hearing_info = models.CharField(default='NA', max_length=500,blank=True)
    locality = models.CharField(default='NA', max_length=500,blank=True)
    name = models.CharField(default='NA', max_length=500,blank=True)
    offense_date = models.CharField(default='NA', max_length=500,blank=True)
    operator_license_restriction_codes = models.CharField(default='NA', max_length=500,blank=True)
    operator_license_suspension_effective_date = models.CharField(default='NA', max_length=500,blank=True)
    operator_license_suspension_time = models.CharField(default='NA', max_length=500,blank=True)
    probation_starts = models.CharField(default='NA', max_length=500,blank=True)
    probation_time = models.CharField(default='NA', max_length=500,blank=True)
    probation_type = models.CharField(default='NA', max_length=500,blank=True)
    race = models.CharField(default='NA', max_length=500,blank=True)
    sentence_suspended_time = models.CharField(default='NA', max_length=500,blank=True)
    sentence_time = models.CharField(default='NA', max_length=500,blank=True)
    status = models.CharField(default='NA', max_length=500,blank=True)
    vasap = models.CharField(default='NA', max_length=500,blank=True)
    def __str__(self):
        """Return a human readable representation of the model instance."""
        return "this is a crim case filed on " + str(self.filed_date) + " dealing with a " + str(self.crim_class) + " for the crime of " + str(self.charge)