from django.db import models


class DistrictCivil(models.Model):

    fips = models.CharField(max_length=3, blank=True, null=True)
    filed_date = models.CharField(max_length=10, blank=True, null=True)
    case_type = models.CharField(max_length=35, blank=True, null=True)
    debt_type = models.CharField(max_length=40, blank=True, null=True)
    judgment = models.CharField(max_length=25, blank=True, null=True)
    costs = models.CharField(max_length=10, blank=True, null=True)
    attorney_fees = models.CharField(max_length=10, blank=True, null=True)
    principal_amount = models.CharField(max_length=10, blank=True, null=True)
    other_amount = models.CharField(max_length=10, blank=True, null=True)
    interest_award = models.CharField(max_length=70, blank=True, null=True)
    possession = models.CharField(max_length=10, blank=True, null=True)
    writ_issued_date = models.CharField(max_length=10, blank=True, null=True)
    homestead_exemption_waived = models.CharField(max_length=3, blank=True, null=True)
    is_judgment_satisfied = models.CharField(max_length=5, blank=True, null=True)
    date_satisfaction_filed = models.CharField(max_length=10, blank=True, null=True)
    other_awarded = models.CharField(max_length=70, blank=True, null=True)
    further_case_information = models.CharField(max_length=65, blank=True, null=True)
    garnishee = models.CharField(max_length=30, blank=True, null=True)
    address = models.CharField(max_length=40, blank=True, null=True)
    garnishee_answer = models.CharField(max_length=15, blank=True, null=True)
    answer_date = models.CharField(max_length=10, blank=True, null=True)
    number_of_checks_received = models.CharField(max_length=5, blank=True, null=True)
    appeal_date = models.CharField(max_length=10, blank=True, null=True)
    appealed_by = models.CharField(max_length=15, blank=True, null=True)
    writ_of_eviction_issued_date = models.CharField(max_length=10, blank=True, null=True)
    writ_of_fieri_facias_issued_date = models.CharField(max_length=3, blank=True, null=True)
    plaintiff_1_DBATA = models.CharField(max_length=50, blank=True, null=True)
    plaintiff_1_address = models.CharField(max_length=40, blank=True, null=True)
    plaintiff_1_attorney = models.CharField(max_length=35, blank=True, null=True)
    plaintiff_2_DBATA = models.CharField(max_length=50, blank=True, null=True)
    plaintiff_2_address = models.CharField(max_length=40, blank=True, null=True)
    plaintiff_2_attorney = models.CharField(max_length=35, blank=True, null=True)
    plaintiff_3_DBATA = models.CharField(max_length=50, blank=True, null=True)
    plaintiff_3_address = models.CharField(max_length=40, blank=True, null=True)
    plaintiff_3_attorney = models.CharField(max_length=35, blank=True, null=True)
    defendant_1_DBATA = models.CharField(max_length=50, blank=True, null=True)
    defendant_1_address = models.CharField(max_length=50, blank=True, null=True)
    defendant_1_attorney = models.CharField(max_length=30, blank=True, null=True)
    defendant_2_DBATA = models.CharField(max_length=50, blank=True, null=True)
    defendant_2_address = models.CharField(max_length=50, blank=True, null=True)
    defendant_2_attorney = models.CharField(max_length=30, blank=True, null=True)
    defendant_3_DBATA = models.CharField(max_length=50, blank=True, null=True)
    defendant_3_address = models.CharField(max_length=50, blank=True, null=True)
    defendant_3_attorney = models.CharField(max_length=30, blank=True, null=True)