# Generated by Django 3.2.5 on 2022-01-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCriminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.CharField(blank=True, max_length=10, null=True)),
                ('hearing_result', models.CharField(blank=True, max_length=9, null=True)),
                ('hearing_plea', models.CharField(blank=True, max_length=17, null=True)),
                ('hearing_continuance_code', models.CharField(blank=True, max_length=22, null=True)),
                ('hearing_type', models.CharField(blank=True, max_length=54, null=True)),
                ('hearing_courtroom', models.CharField(blank=True, max_length=4, null=True)),
                ('fips', models.CharField(blank=True, max_length=3, null=True)),
                ('filed_date', models.CharField(blank=True, max_length=10, null=True)),
                ('locality', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=24, null=True)),
                ('defense_attorney', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('race', models.CharField(blank=True, max_length=42, null=True)),
                ('charge', models.CharField(blank=True, max_length=57, null=True)),
                ('code_section', models.CharField(blank=True, max_length=15, null=True)),
                ('case_type', models.CharField(blank=True, max_length=53, null=True)),
                ('offense_class', models.CharField(blank=True, max_length=3, null=True)),
                ('offense_date', models.CharField(blank=True, max_length=10, null=True)),
                ('arrest_date', models.CharField(blank=True, max_length=10, null=True)),
                ('complainant', models.CharField(blank=True, max_length=30, null=True)),
                ('amended_charge', models.CharField(blank=True, max_length=55, null=True)),
                ('amended_code', models.CharField(blank=True, max_length=15, null=True)),
                ('amended_case_type', models.CharField(blank=True, max_length=53, null=True)),
                ('final_disposition', models.CharField(blank=True, max_length=41, null=True)),
                ('sentence_time', models.CharField(blank=True, max_length=5, null=True)),
                ('sentence_suspended_time', models.CharField(blank=True, max_length=5, null=True)),
                ('probation_type', models.CharField(blank=True, max_length=22, null=True)),
                ('probation_time', models.CharField(blank=True, max_length=7, null=True)),
                ('probation_starts', models.CharField(blank=True, max_length=48, null=True)),
                ('operator_license_suspension_time', models.CharField(blank=True, max_length=7, null=True)),
                ('restriction_effective_date', models.CharField(blank=True, max_length=10, null=True)),
                ('restriction_end_date', models.CharField(blank=True, max_length=10, null=True)),
                ('operator_license_restriction_codes', models.CharField(blank=True, max_length=767, null=True)),
                ('fine', models.CharField(blank=True, max_length=7, null=True)),
                ('costs', models.CharField(blank=True, max_length=8, null=True)),
                ('fine_costs_due', models.CharField(blank=True, max_length=10, null=True)),
                ('fine_costs_paid', models.CharField(blank=True, max_length=3, null=True)),
                ('fine_costs_paid_date', models.CharField(blank=True, max_length=10, null=True)),
                ('vasap', models.CharField(blank=True, max_length=3, null=True)),
                ('fine_costs_past_due', models.CharField(blank=True, max_length=3, null=True)),
                ('person_id', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
